### ISSUE TITLE
multiple form in one page problem

### ISSUE THREAD

**Issue by fariborzasgarpour** [timothyjensen/gravityformsadvancedselect#4] opened 2024-03-07 23:18 UTC
Hello
Thanks for this great plugin
There is a problem when we have 2 forms on the same page and this plugin is used in its fields
We get a JavaScript mismatch problem and an error
![image](https://github.com/timothyjensen/gravityformsadvancedselect/assets/53476655/6fa82ae5-f6a0-453b-9218-20d8aa2b1a2b)

**Comment by timothyjensen** [comment] 2024-03-08 00:25
Thanks for reporting this problem. The issue is resolved in version 0.2.5.

**Closed as completed** 2024-03-08 00:24 UTC
